const SAVE_MESSAGES = 'SAVE_MESSAGES'
const DELETE_MESSAGES = 'DELETE_MESSAGES'
const TOGGLE_MESSAGES_LOADING = 'TOGGLE_MESSAGES_LOADING'
const UPDATE_CHAT_PAGE = 'UPDATE_CHAT_PAGE'
const TOGGLE_IS_LOADING_MORE = 'TOGGLE_IS_LOADING_MORE'
const RESET_PAGE = 'RESET_PAGE'

export default {
  SAVE_MESSAGES,
  DELETE_MESSAGES,
  TOGGLE_MESSAGES_LOADING,
  UPDATE_CHAT_PAGE,
  TOGGLE_IS_LOADING_MORE,
  RESET_PAGE
}
