const SAVE_MESSAGES = 'SAVE_MESSAGES'
const DELETE_MESSAGES = 'DELETE_MESSAGES'
const TOGGLE_MESSAGES_LOADING = 'TOGGLE_MESSAGES_LOADING'

export default {
  SAVE_MESSAGES,
  DELETE_MESSAGES,
  TOGGLE_MESSAGES_LOADING
}
