const GET_CHATS = 'GET_CHATS'
const TOGGLE_CHATS_LOADING = 'TOGGLE_CHATS_LOADING'
const GET_USERS = 'GET_USERS'
const DELETE_USERS = 'DELETE_USERS'

export default {
  GET_CHATS,
  TOGGLE_CHATS_LOADING,
  GET_USERS,
  DELETE_USERS
}
