const GET_CHATS = 'GET_CHATS'
const TOGGLE_CHATS_LOADING = 'TOGGLE_CHATS_LOADING'
const GET_USERS = 'GET_USERS'
const DELETE_USERS = 'DELETE_USERS'
const CREATE_CHAT = 'CREATE_CHAT'
const UPDATE_CHAT = 'UPDATE_CHAT'
const RESET_CHATS = 'RESET_CHATS'
const SAVE_CHOSEN_USERS = 'SAVE_CHOSEN_USERS'

export default {
  GET_CHATS,
  TOGGLE_CHATS_LOADING,
  GET_USERS,
  DELETE_USERS,
  CREATE_CHAT,
  RESET_CHATS,
  UPDATE_CHAT,
  SAVE_CHOSEN_USERS
}
