const SAVE_COMMENTS_DATA = 'SAVE_COMMENTS_DATA'
const TOGGLE_COMMENTS_LOADING = 'TOGGLE_COMMENTS_LOADING'
const RESET_COMMENTS_DATA = 'RESET_COMMENTS_DATA'

export default {
  SAVE_COMMENTS_DATA,
  TOGGLE_COMMENTS_LOADING,
  RESET_COMMENTS_DATA
}
