const SAVE_COMMENTS_DATA = 'SAVE_COMMENTS_DATA'
const TOGGLE_COMMENTS_LOADING = 'TOGGLE_COMMENTS_LOADING'
const RESET_COMMENTS_DATA = 'RESET_COMMENTS_DATA'
const ADD_COMMENT = 'ADD_COMMENT'
const UPDATE_COMMENT = 'UPDATE_COMMENT'
const EDIT_COMMENT = 'EDIT_COMMENT'
const CANCEL_EDITING = 'CANCEL_EDITING'

export default {
  SAVE_COMMENTS_DATA,
  EDIT_COMMENT,
  CANCEL_EDITING,
  TOGGLE_COMMENTS_LOADING,
  RESET_COMMENTS_DATA,
  ADD_COMMENT,
  UPDATE_COMMENT
}
