const SAVE_LOCATIONS = 'SAVE_LOCATIONS'
const TOGGLE_LOADING = 'TOGGLE_LOADING'
const RESET_LOCATIONS = 'RESET_LOCATIONS'
const SAVE_LOCATION = 'SAVE_LOCATION'

export default {
  SAVE_LOCATIONS,
  TOGGLE_LOADING,
  RESET_LOCATIONS,
  SAVE_LOCATION
}
