const SAVE_LOCATIONS = 'SAVE_LOCATIONS'
const TOGGLE_LOADING = 'TOGGLE_LOADING'
const RESET_LOCATIONS = 'RESET_LOCATIONS'
const SAVE_LOCATION_OBJ = 'SAVE_LOCATION_OBJ'
const DELETE_LOCATION_OBJ = 'DELETE_LOCATION_OBJ'

export default {
  SAVE_LOCATIONS,
  TOGGLE_LOADING,
  RESET_LOCATIONS,
  SAVE_LOCATION_OBJ,
  DELETE_LOCATION_OBJ
}
