const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS'
const UPDATE_CABLE_CONNECTION_STATUS = 'UPDATE_CABLE_CONNECTION_STATUS'

export default {
  UPDATE_CONNECTION_STATUS,
  UPDATE_CABLE_CONNECTION_STATUS
}
