const SAVE_LINK = 'SAVE_LINK'
const CLEAR_LINK = 'CLEAR_LINK'
const TOGGLE_TOPIC = 'TOGGLE_TOPIC'
const SAVE_CONTENT = 'SAVE_CONTENT'
const TOGGLE_COMMENTS = 'TOGGLE_COMMENTS'
const TOGGLE_PRIVACY = 'TOGGLE_PRIVACY'
const RESET_POST = 'RESET_POST'
const SAVE_GROUP = 'SAVE_GROUP'
const DELETE_GROUP = 'DELETE_GROUP'
const SET_IMAGE = 'SET_IMAGE'

export default {
  SAVE_LINK,
  CLEAR_LINK,
  TOGGLE_TOPIC,
  SAVE_CONTENT,
  TOGGLE_COMMENTS,
  TOGGLE_PRIVACY,
  RESET_POST,
  SAVE_GROUP,
  DELETE_GROUP,
  SET_IMAGE
}
