const SAVE_LINK = 'SAVE_LINK'
const TOGGLE_TOPIC = 'TOGGLE_TOPIC'
const SAVE_CONTENT = 'SAVE_CONTENT'
const TOGGLE_COMMENTS = 'TOGGLE_COMMENTS'
const TOGGLE_PRIVACY = 'TOGGLE_PRIVACY'
const RESET_POST = 'RESET_POST'
const SAVE_GROUP = 'SAVE_GROUP'
const DELETE_GROUP = 'DELETE_GROUP'
const SAVE_LOCATION = 'SAVE_LOCATION'
const DELETE_LOCATION = 'DELETE_LOCATION'
const SAVE_POST_TO_MODIFY = 'SAVE_POST_TO_MODIFY'
const DELETE_IMAGE_DATA = 'DELETE_IMAGE_DATA'

export default {
  SAVE_LINK,
  TOGGLE_TOPIC,
  SAVE_CONTENT,
  TOGGLE_COMMENTS,
  TOGGLE_PRIVACY,
  RESET_POST,
  SAVE_GROUP,
  DELETE_GROUP,
  SAVE_LOCATION,
  DELETE_LOCATION,
  SAVE_POST_TO_MODIFY,
  DELETE_IMAGE_DATA
}
