const SAVE_PUBLIC_USER_DATA = 'SAVE_PUBLIC_USER_DATA'
const CLEAR_PUBLIC_USER_DATA = 'CLEAR_PUBLIC_USER_DATA'
const TOGGLE_PUBLIC_USER_LOADING = 'TOGGLE_PUBLIC_USER_LOADING'

export default {
  SAVE_PUBLIC_USER_DATA,
  CLEAR_PUBLIC_USER_DATA,
  TOGGLE_PUBLIC_USER_LOADING
}
