const SAVE_RESEARCH_FEED_DATA = 'SAVE_RESEARCH_FEED_DATA'
const TOGGLE_RESEARCH_FEED_LOADING = 'TOGGLE_RESEARCH_FEED_LOADING'
const UPDATE_RESEARCH_FEED_PAGE = 'UPDATE_RESEARCH_FEED_PAGE'

export default {
  SAVE_RESEARCH_FEED_DATA,
  TOGGLE_RESEARCH_FEED_LOADING,
  UPDATE_RESEARCH_FEED_PAGE
}
