const SAVE_RESEARCH_FEED_DATA = 'SAVE_RESEARCH_FEED_DATA'
const TOGGLE_RESEARCH_FEED_LOADING = 'TOGGLE_RESEARCH_FEED_LOADING'

export default {
  SAVE_RESEARCH_FEED_DATA,
  TOGGLE_RESEARCH_FEED_LOADING
}
