const SAVE_USER_DATA = 'SAVE_USER_DATA'
const TOGGLE_USER_DATA_LOADING = 'TOGGLE_USER_DATA_LOADING'
const CLEAR_USER_DATA = 'CLEAR_USER_DATA'

export default {
  SAVE_USER_DATA,
  TOGGLE_USER_DATA_LOADING,
  CLEAR_USER_DATA
}
