const SAVE_USER_DATA = 'SAVE_USER_DATA'
const TOGGLE_USER_DATA_LOADING = 'TOGGLE_USER_DATA_LOADING'
const SAVE_FEED_DATA = 'SAVE_FEED_DATA'
const TOGGLE_FEED_DATA_LOADING = 'TOGGLE_FEED_DATA_LOADING'

export default {
  SAVE_USER_DATA,
  TOGGLE_USER_DATA_LOADING,
  SAVE_FEED_DATA,
  TOGGLE_FEED_DATA_LOADING
}
